const citiesByCountry = {
  Turkey: [
    "Istanbul",
    "Ankara",
    "Izmir",
    "Antalya",
    "Bursa",
    "Adana",
    "Mersin",
    "Trabzon",
    "Samsun",
    "Erzurum",
    "Konya",
    "Diyarbakir",
    "Gaziantep",
    "Malatya",
    "Van",
    "Eskisehir",
  ],
  USA: [
    "New York",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "San Jose",
    "Austin",
    "Jacksonville",
    "San Francisco",
    "Indianapolis",
    "Columbus",
    "Fort Worth",
  ],
  Germany: [
    "Berlin",
    "Hamburg",
    "Munich",
    "Cologne",
    "Frankfurt",
    "Stuttgart",
    "Dusseldorf",
    "Dortmund",
    "Essen",
    "Leipzig",
    "Bremen",
    "Dresden",
    "Hanover",
    "Nuremberg",
    "Duisburg",
    "Bochum",
  ],
  France: [
    "Paris",
    "Marseille",
    "Lyon",
    "Toulouse",
    "Nice",
    "Nantes",
    "Strasbourg",
    "Montpellier",
    "Bordeaux",
    "Lille",
    "Rennes",
    "Reims",
    "Le Havre",
    "Saint Etienne",
    "Toulon",
    "Grenoble",
  ],
  Italy: [
    "Rome",
    "Milan",
    "Naples",
    "Turin",
    "Palermo",
    "Genoa",
    "Bologna",
    "Florence",
    "Bari",
    "Catania",
    "Venice",
    "Verona",
    "Messina",
    "Padua",
    "Trieste",
    "Brescia",
  ],
  Spain: [
    "Madrid",
    "Barcelona",
    "Valencia",
    "Seville",
    "Zaragoza",
    "Malaga",
    "Murcia",
    "Palma",
    "Las Palmas",
    "Bilbao",
    "Alicante",
    "Cordoba",
    "Valladolid",
    "Vigo",
    "Gijon",
    "Hospitalet de Llobregat",
  ],
  UK: [
    "London",
    "Birmingham",
    "Manchester",
    "Glasgow",
    "Newcastle",
    "Sheffield",
    "Liverpool",
    "Leeds",
    "Bristol",
    "Edinburgh",
    "Leicester",
    "Coventry",
    "Bradford",
    "Cardiff",
    "Belfast",
    "Nottingham",
  ],
  Greece: [
    "Athens",
    "Thessaloniki",
    "Patras",
    "Heraklion",
    "Larissa",
    "Volos",
    "Rhodes",
    "Ioannina",
    "Chania",
    "Chalcis",
    "Kavala",
    "Trikala",
    "Serres",
    "Lamia",
    "Alexandroupoli",
    "Katerini",
  ],
  Russia: [
    "Moscow",
    "Saint Petersburg",
    "Novosibirsk",
    "Yekaterinburg",
    "Nizhny Novgorod",
    "Samara",
    "Omsk",
    "Kazan",
    "Chelyabinsk",
    "Rostov-on-Don",
    "Ufa",
    "Volgograd",
    "Perm",
    "Krasnoyarsk",
    "Voronezh",
    "Saratov",
  ],
  China: [
    "Beijing",
    "Shanghai",
    "Guangzhou",
    "Shenzhen",
    "Tianjin",
    "Wuhan",
    "Dongguan",
    "Chongqing",
    "Chengdu",
    "Nanjing",
    "Shenyang",
    "Hangzhou",
    "Xi'an",
    "Harbin",
    "Suzhou",
    "Dalian",
  ],
  Japan: [
    "Tokyo",
    "Yokohama",
    "Osaka",
    "Nagoya",
    "Sapporo",
    "Fukuoka",
    "Kobe",
    "Kyoto",
    "Kawasaki",
    "Saitama",
    "Hiroshima",
    "Sendai",
    "Chiba",
    "Kitakyushu",
    "Naha",
    "Okayama",
  ],
  "South Korea": [
    "Seoul",
    "Busan",
    "Incheon",
    "Daegu",
    "Daejeon",
    "Gwangju",
    "Ulsan",
    "Suwon",
    "Changwon",
    "Seongnam",
    "Goyang",
    "Yongin",
    "Cheongju",
    "Jeonju",
    "Cheonan",
    "Asan",
  ],
  Brazil: [
    "Brasilia",
    "Sao Paulo",
    "Rio de Janeiro",
    "Salvador",
    "Fortaleza",
    "Belo Horizonte",
    "Manaus",
    "Curitiba",
    "Recife",
    "Porto Alegre",
    "Goiania",
    "Belem",
    "Guarulhos",
    "Campinas",
    "Nova Iguacu",
    "Sao Luis",
  ],
  Argentina: [
    "Buenos Aires",
    "Cordoba",
    "Rosario",
    "Mendoza",
    "Tucuman",
    "La Plata",
    "Mar del Plata",
    "Salta",
    "Santa Fe",
    "San Juan",
    "Resistencia",
    "Neuquen",
    "Corrientes",
    "Posadas",
    "Parana",
    "Bahia Blanca",
  ],
};

exports.citiesByCountry = citiesByCountry;